duel/urls.py
from django.urls import path

from . import views

app_name = 'duel'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('match-list/', views.MatchListView.as_view(), name="match_list"),
    path('match-detail/<int:pk>', views.MatchDetailView.as_view(), name="match_detail"),
    path('match-create/', views.MatchCreateView.as_view(), name="match_create"),
    path('match-update/<int:pk>/', views.MatchUpdateView.as_view(), name="match_update"),
    path('match-delete/<int:pk>/', views.MatchDeleteView.as_view(), name="match_delete"),
    path('player-list/', views.PlayerListView.as_view(), name="player_list"),
    path('player-detail/<int:pk>', views.PlayerDetailView.as_view(), name="player_detail"),
    path('player-create/', views.PlayerCreateView.as_view(), name="player_create"),
    path('player-update/<int:pk>/', views.PlayerUpdateView.as_view(), name="player_update"),
    path('player-delete/<int:pk>/', views.PlayerDeleteView.as_view(), name="player_delete"),
    path('team-create/', views.TeamCreateView.as_view(), name="team_create"),
    path('team-config/', views.TeamConfigView.as_view(), name="team_config"),
]

entrance/urls.py
from django.urls import path

from . import views

app_name = 'entrance'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('rating-system', views.RatingSystemView.as_view(), name="rating_system"),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
]

rankmaker/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import settings_common, settings_dev

urlpatterns = [
    path('kanri/', admin.site.urls),
    path('duel/', include('duel.urls')),
    path('multi/', include('multi.urls')),
    path('', include('entrance.urls')),
    path('accounts/', include('allauth.urls')),
    path("ads.txt", TemplateView.as_view(template_name='ads.txt', content_type='text/plain')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(
    settings_common.MEDIA_URL,
    document_root=settings_dev.MEDIA_ROOT,
)

duel/forms.py
import logging
import os

from django import forms
from django.core.mail import EmailMessage

from .models import Match, Player, Affiliation, Team
from django.core.exceptions import ValidationError


class CustomModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj):  # label_from_instance 関数をオーバーライド
        return obj.name


class MatchCreateForm(forms.ModelForm):
    winner = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        label='勝者',
        empty_label='選択してください',
        to_field_name='name',
    )
    loser = forms.ModelChoiceField(
        queryset=Player.objects.all(),
        label='敗者',
        empty_label='選択してください',
        to_field_name='name',
    )
    even = forms.BooleanField(
        label='引き分け',
        initial=None,
        required=False,
    )

    class Meta:
        model = Match
        fields = ('winner', 'loser', 'even', 'date',)

    def __init__(self, *args, **kwargs):
        match = kwargs['instance']
        if match:
            kwargs['initial'] = {'winner': match.winner, 'loser': match.loser}
        userteam = kwargs.pop('team')
        self.base_fields["winner"].queryset = Player.objects.filter(team=userteam)
        self.base_fields["loser"].queryset = Player.objects.filter(team=userteam)
        super().__init__(*args, **kwargs)
        # for field in self.fields.values():
            # if field.name != 'even':
                # field.widget.attrs['class'] = 'form-control'

    def clean(self):
        winner = self.cleaned_data['winner']
        loser = self.cleaned_data['loser']
        if winner == loser:
            raise ValidationError('勝者と敗者は異なる人物にしてください')


class PlayerCreateForm(forms.ModelForm):
    name = forms.CharField(label='名前', max_length=30)

    class Meta:
        model = Player
        fields = ('name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class TeamCreateForm(forms.ModelForm):
    name = forms.CharField(label='チーム名', max_length=30)

    class Meta:
        model = Team
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'


class TeamConfigForm(forms.ModelForm):
    name = forms.CharField(label='チーム名', max_length=30)

    class Meta:
        model = Team
        fields = ('name', 'description')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

duel/views.py
import logging
from django.urls import reverse_lazy
from django.views import generic
from .forms import MatchCreateForm, PlayerCreateForm, TeamCreateForm, TeamConfigForm
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin

from .rating_functions import refresh_ratings
from .models import Match, Team, Rating, Player, Affiliation
from accounts.models import CustomUser

# Create your views here.
logger = logging.getLogger(__name__)


class HomeView(LoginRequiredMixin, generic.TemplateView):
    template_name = "duel/home.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['username'] = self.request.user

        if Affiliation.objects.filter(user=self.request.user).count() != 0:
            affl = Affiliation.objects.get(user=self.request.user)
            refresh_ratings(affl.team)
            players = Player.objects.filter(team=affl.team).order_by('-latest_rating')
            context['ranking'] = players
            context['team'] = affl.team
        else:
            context['ranking'] = Player.objects.none()

        return context


class MatchListView(LoginRequiredMixin, generic.ListView):
    model = Match
    template_name = 'duel/match_list.html'
    paginate_by = 5

    def get_queryset(self):
        affl = Affiliation.objects.get(user=self.request.user)
        refresh_ratings(affl.team)
        matches = Match.objects.filter(team=affl.team).order_by('-date')
        return matches

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        refresh_ratings(affl.team)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context


class MatchDetailView(LoginRequiredMixin, generic.DetailView):
    model = Match
    template_name = 'duel/match_detail.html'

#    def get_context_data(self, **kwargs):
#        affl = Affiliation.objects.get(user=self.request.user)
#        context = super().get_context_data(**kwargs)
#        context['team'] = affl.team
#        return context


class MatchCreateView(LoginRequiredMixin, generic.CreateView):
    model = Match
    template_name = 'duel/match_create.html'
    form_class = MatchCreateForm
    success_url = reverse_lazy('duel:match_list')

    def get_form_kwargs(self, *args, **kwargs):
        kwgs = super(MatchCreateView, self).get_form_kwargs(*args, **kwargs)
        affl = Affiliation.objects.get(user=self.request.user)
        kwgs["team"] = affl.team
        return kwgs

    def form_valid(self, form):  # formのバリデーションに問題がなければ実行
        match = form.save(commit=False)  # userの入力が必須だが、ユーザーにそれを入力させるのは自明なのでおかしい。テクニック。
        affl = Affiliation.objects.get(user=self.request.user)
        match.team = affl.team
        match.save()
        # 勝者のレーティングを計算せず登録
        winrate = Rating()
        winrate.match = match
        winrate.player = match.winner
        winrate.save()
        # 敗者のレーティングを計算せず登録
        losrate = Rating()
        losrate.match = match
        losrate.player = match.loser
        losrate.save()
        # 仮レーティングは表示時に再計算して評価される

        messages.success(self.request, "対戦結果を登録しました。")
        return super().form_valid(form)

    def form_invalid(self, form):  # formのバリデーションに問題があるときに実行
        messages.error(self.request, "対戦結果の登録に失敗しました。")
        return super().form_invalid(form)


class MatchUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Match
    template_name = 'duel/match_update.html'
    form_class = MatchCreateForm

    def get_form_kwargs(self, *args, **kwargs):
        kwgs = super(MatchUpdateView, self).get_form_kwargs(*args, **kwargs)
        affl = Affiliation.objects.get(user=self.request.user)
        kwgs["team"] = affl.team

        return kwgs

    def get_success_url(self):
        return reverse_lazy('duel:match_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        match = form.save(commit=False)
        match.save()

        messages.success(self.request, '対戦結果を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "対戦結果の更新に失敗しました。")
        return super().form_invalid(form)


class MatchDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Match
    template_name = 'duel/match_delete.html'
    success_url = reverse_lazy('duel:match_list')

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "対戦結果を削除しました。")
        return super().delete(request, *args, **kwargs)


class PlayerListView(LoginRequiredMixin, generic.ListView):
    model = Player
    template_name = 'duel/player_list.html'
    paginate_by = 30

    def get_queryset(self):
        affl = Affiliation.objects.get(user=self.request.user)
        refresh_ratings(affl.team)
        players = Player.objects.filter(team=affl.team).order_by('pk')
        return players

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        refresh_ratings(affl.team)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context


class PlayerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Player
    template_name = 'duel/player_detail.html'

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context


class PlayerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Player
    template_name = 'duel/player_create.html'
    form_class = PlayerCreateForm
    success_url = reverse_lazy('duel:player_list')

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context

    def form_valid(self, form):  # formのバリデーションに問題がなければ実行
        player = form.save(commit=False)
        affl = Affiliation.objects.get(user=self.request.user)
        player.team = affl.team
        player.save()
        messages.success(self.request, "メンバーを追加しました。")
        return super().form_valid(form)

    def form_invalid(self, form):  # formのバリデーションに問題があるときに実行
        messages.error(self.request, "メンバーの追加に失敗しました。")
        return super().form_invalid(form)


class PlayerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Player
    template_name = 'duel/player_update.html'
    form_class = PlayerCreateForm

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context

    def get_success_url(self):
        return reverse_lazy('duel:player_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, 'メンバーを更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "メンバーの更新に失敗しました。")
        return super().form_invalid(form)


class PlayerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Player
    template_name = 'duel/player_delete.html'
    success_url = reverse_lazy('duel:player_list')

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "メンバーを削除しました。")
        return super().delete(request, *args, **kwargs)


class TeamCreateView(LoginRequiredMixin, generic.CreateView):
    model = Team
    template_name = 'duel/team_create.html'
    form_class = TeamCreateForm
    success_url = reverse_lazy('duel:player_list')

    def form_valid(self, form):  # formのバリデーションに問題がなければ実行
        team = form.save(commit=False)
        team.save()
        affl = Affiliation()
        affl.team = team
        affl.user = self.request.user
        affl.save()
        self.request.user.have_duel_team = True
        self.request.user.save()

        messages.success(self.request, "チームを作成しました。")
        return super().form_valid(form)

    def form_invalid(self, form):  # formのバリデーションに問題があるときに実行
        messages.error(self.request, "チームの作成に失敗しました。")
        return super().form_invalid(form)


class TeamConfigView(LoginRequiredMixin, generic.UpdateView):
    model = Team
    template_name = 'duel/team_config.html'
    form_class = TeamConfigForm
    success_url = reverse_lazy('duel:home')

    def get_object(self, queryset=None):
        return Affiliation.objects.get(user=self.request.user).team

    def get_context_data(self, **kwargs):
        affl = Affiliation.objects.get(user=self.request.user)
        context = super().get_context_data(**kwargs)
        context['team'] = affl.team
        return context

    def form_valid(self, form):
        messages.success(self.request, 'チーム設定を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "チーム設定の更新に失敗しました。")
        return super().form_invalid(form)

duel/templates/duel/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
          rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet"/>

    <!-- Core theme CSS (includes Bootstrap)-->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <!-- My Style -->
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet"/>
    {% block head %}{% endblock %}
</head>

<body>
<div id="wrapper">
    <!-- Navigation-->

    <nav class="navbar navbar-light bg-light fixed-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% if user.is_authenticated %}{% url 'duel:home' %}{% else %}{% url 'entrance:index' %}{% endif %}">ランクメーカー</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto">
                    {% if user.is_authenticated %}
                    {% if user.have_team %}
                    <li class="nav-item">
                        <a href="{% url 'duel:match_list' %}" class="nav-link {% block active_match_list %}{% endblock %}">対戦結果一覧</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'duel:player_list' %}" class="nav-link {% block active_player_list %}{% endblock %}">メンバー一覧</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'duel:team_config' %}" class="nav-link {% block active_team_config %}{% endblock %}">チーム設定</a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% block activate_signup %}{% endblock %}" href="{% url 'account_signup' %}">新規登録</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block activate_login %}{% endblock %}"  href="{% url 'account_login' %}">ログイン</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link {% block active_inquiry %}{% endblock %}" href="{% url 'entrance:inquiry' %}">ご意見</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    {% block header %}{% endblock %}

    {% if messages %}
        <div class="container my-div-style">
            <div class="row">
                <ul class="messages" style="list-style: none;">
                    {% for message in messages %}

                    <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                        {{ message }}
                    </li>

                    {% endfor %}
                </ul>
            </div>
        </div>
    {% endif %}

    {% block contents %}{% endblock %}

    <!-- Footer-->
    <footer class="py-5 bg-black">
        <div class="container px-5"><p class="m-0 text-center text-white small">Copyright &copy; ランクメーカー 2022</p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</div>
</body>
</html>

duel/templates/duel/home.html
{% extends 'duel/base.html' %}

{% load static %}

{% block title %}ランクメーカー{% endblock %}

{% block header %}

{% endblock %}

{% block contents %}
{% if user.is_authenticated %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h2>{{ username }}さん、ようこそ</h2>
            <div>
                {% if user.have_team %}
                <table class="table">
                    <tr>
                        <th>順位</th>
                        <th>名前</th>
                        <th>レーティング</th>
                    </tr>

                    {% for player in ranking %}
                    <tr>
                        <th>{{ forloop.counter }}</th>
                        <td>{{ player.name }}</td>
                        <td>{{ player.latest_rating }}</td>
                    </tr>
                    {% empty %}
                    <tr><td colspan="3">メンバーが登録されていません。<a href="{% url 'duel:player_create' %}">メンバーの登録はこちらから。</a></td></tr>
                    {% endfor %}
                </table>
                {% else %}
                <p class="">チームが作成されていません。<br>
                        <a href="{% url 'duel:team_create' %}">こちらからから作成してください。</a>
                </p>
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endif %}
{% endblock %}

duel/templates/duel/match_detail.html
{% extends 'duel/base.html' %}
{% load static %}

{% block title %}対戦結果詳細 | ランクメーカー{% endblock %}

{% block active_match_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>勝者ID</strong>
        </div>
        <div class="col-9">
            {{ object.winner }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>敗者ID</strong>
        </div>
        <div class="col-9">
            {{ object.loser }}
        </div>
    </div>

    <hr>

        <div class="row">
        <div class="col-3">
            <strong>引き分け</strong>
        </div>
        <div class="col-9">
            {{ object.even }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>試合日時</strong>
        </div>
        <div class="col-9">
            {{ object.date }}
        </div>
    </div>

        <hr>


    <a href="{% url 'duel:match_update' object.pk %}" class="btn btn-primary mt-5 mb-3">編集</a>
    <a href="{% url 'duel:match_delete' object.pk %}" class="btn btn-danger mt-5 mb-3 ml-2">削除</a>
    <a href="{% url 'duel:match_list' %}" class="btn btn-secondary mt-5 mb-3">戻る</a>
</div>
{% endblock %}

duel/templates/duel/match_list.html
{% extends 'duel/base.html' %}
{% load static %}

{% block title %}対戦結果一覧 | ランクメーカー{% endblock %}

{% block active_match_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.css' %}">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h1>{{ team }}の対戦結果一覧</h1>
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'duel:match_create' %}">対戦結果登録</a>
            </div>
            {% for match in match_list %}
            <div class="post-preview">
                <a href="{% url 'duel:match_detail' match.pk %}"><!--pk=プライマリキー-->
                    <h2 class="post-subtitle">
                        {{ match.pk }} : {{ match.winner }} VS {{ match.loser }}
                    </h2>
                </a>
                <div class="post-meta">{{ match.date }}　{{ match.winner }}:{{ match.winner_old_rating_disp }}
                    →{{ match.winner_new_rating_disp }}　{{ match.loser }}:{{ match.loser_old_rating_disp }}→{{ match.loser_new_rating_disp }}</div>
            </div>
            <hr class="my-3">
            {% empty %}
            <p>対戦結果がありません。</p>
            {% endfor %}

            <!--  ページネーション処理  -->
            {% if is_paginated %}
            <ul class="pagination">
                <!--前ページへのリンク-->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!--ページ数表示-->
                {% for page_num in page_obj.paginator.page_range %}
                    {% if page_obj.number == page_num %}
                    <li class="page-item active">
                        <a href="#" class="page-link">{{page_num}}</a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{ page_num }}" class="page-link">{{page_num}}</a>
                    </li>
                    {% endif %}
                {% endfor %}

                <!--次ページへのリンク-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

duel/templates/duel/player_detail.html
{% extends 'duel/base.html' %}
{% load static %}

{% block title %}対戦結果詳細 | ランクメーカー{% endblock %}

{% block active_player_list %}active{% endblock %}

{% block contents %}
<div class="container my-div-style">
    <div class="row">
        <div class="col-3">
            <strong>ID</strong>
        </div>
        <div class="col-9">
            {{ object.id }}
        </div>
    </div>

    <hr>

    <div class="row">
        <div class="col-3">
            <strong>名前</strong>
        </div>
        <div class="col-9">
            {{ object.name }}
        </div>
    </div>

        <hr>

    <div class="row">
        <div class="col-3">
            <strong>対戦数</strong>
        </div>
        <div class="col-9">
            {{ object.match_exp }}試合
        </div>
    </div>

    <a href="{% url 'duel:player_update' object.pk %}" class="btn btn-primary mt-5 mb-3">編集</a>
    <a href="{% url 'duel:player_delete' object.pk %}" class="btn btn-danger mt-5 mb-3 ml-2">削除</a>
    <a href="{% url 'duel:player_list' %}" class="btn btn-secondary mt-5 mb-3">戻る</a>
</div>
{% endblock %}

duel/templates/duel/player_list.html
{% extends 'duel/base.html' %}
{% load static %}

{% block title %}チーム設定 | ランクメーカー{% endblock %}

{% block active_player_list %}active{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/clean-blog.css' %}">
{% endblock %}

{% block contents %}
<div class="container px-4 px-lg-5 my-div-style">
    <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-md-10 col-lg-8 col-xl-7">
            <h1>{{ team }}　メンバーリスト</h1>
            <div class="d-flex justify-content-end mb-4">
                <a class="btn btn-primary float-right" href="{% url 'duel:player_create' %}">新規プレイヤー</a>
            </div>
            <table class="table">
                <tr>
                    <th>id</th>
                    <th>プレイヤー名</th>
                    <th>対戦数</th>
                    <th></th>
                </tr>
                {% for player in player_list %}
                <tr>
                    <th>{{ player.id }}</th>
                    <td>{{ player.name }}</td>
                    <td>{{ player.match_exp }}</td>
                    <td><a href="{% url 'duel:player_detail' player.pk %}">詳細</a></td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">メンバーが登録されていません。</td>
                </tr>
                {% endfor %}
            </table>


            <!--  ページネーション処理  -->
            {% if is_paginated %}
            <ul class="pagination">
                <!--前ページへのリンク-->
                {% if page_obj.has_previous %}
                <li class="page-item">
                    <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                {% endif %}

                <!--ページ数表示-->
                {% for page_num in page_obj.paginator.page_range %}
                {% if page_obj.number == page_num %}
                <li class="page-item active">
                    <a href="#" class="page-link">{{page_num}}</a>
                </li>
                {% else %}
                <li class="page-item">
                    <a href="?page={{ page_num }}" class="page-link">{{page_num}}</a>
                </li>
                {% endif %}
                {% endfor %}

                <!--次ページへのリンク-->
                {% if page_obj.has_next %}
                <li class="page-item">
                    <a href="?page={{ page_obj.next_page_number }}" class="page-link">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
                {% endif %}
            </ul>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}