duel/urls.py
from django.urls import path

from . import views

app_name = 'duel'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('match-list/', views.MatchListView.as_view(), name="match_list"),
    path('match-detail/<int:pk>', views.MatchDetailView.as_view(), name="match_detail"),
    path('match-create/', views.MatchCreateView.as_view(), name="match_create"),
    path('match-update/<int:pk>/', views.MatchUpdateView.as_view(), name="match_update"),
    path('match-delete/<int:pk>/', views.MatchDeleteView.as_view(), name="match_delete"),
    path('player-list/', views.PlayerListView.as_view(), name="player_list"),
    path('player-detail/<int:pk>', views.PlayerDetailView.as_view(), name="player_detail"),
    path('player-create/', views.PlayerCreateView.as_view(), name="player_create"),
    path('player-update/<int:pk>/', views.PlayerUpdateView.as_view(), name="player_update"),
    path('player-delete/<int:pk>/', views.PlayerDeleteView.as_view(), name="player_delete"),
    path('team-create/', views.TeamCreateView.as_view(), name="team_create"),
    path('team-config/', views.TeamConfigView.as_view(), name="team_config"),
]

entrance/urls.py
from django.urls import path

from . import views

app_name = 'entrance'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('rating-system', views.RatingSystemView.as_view(), name="rating_system"),
    path('privacy-policy', views.PrivacyPolicyView.as_view(), name="privacy_policy"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
]

multi/urls.py
from django.urls import path

from . import views

app_name = 'multi'
urlpatterns = [
    path('home/', views.HomeView.as_view(), name="home"),
    path('ranking/', views.RankingView.as_view(), name="ranking"),
    path('ranking-ext/<page_id>/', views.RankingExtView.as_view(), name="ranking_ext"),
    path('game-list/', views.GameListView.as_view(), name="game_list"),
    path('su-game-list/', views.SUGameListView.as_view(), name="su_game_list"),
    path('game-detail/<int:pk>', views.GameDetailView.as_view(), name="game_detail"),
    path('game-create/', views.GameCreateView.as_view(), name="game_create"),
    path('batch-game-create/', views.BatchGameCreateView.as_view(), name="batch_game_create"),
    path('game-create-1on1/', views.GameCreate1on1View.as_view(), name="game_create_1on1"),
    path('game-update/<int:pk>/', views.GameUpdateView.as_view(), name="game_update"),
    path('game-update-1on1/<int:pk>/', views.GameUpdate1on1View.as_view(), name="game_update_1on1"),
    path('game-delete/<int:pk>/', views.GameDeleteView.as_view(), name="game_delete"),
    path('player-list/', views.PlayerListView.as_view(), name="player_list"),
    path('player-detail/<int:pk>', views.PlayerDetailView.as_view(), name="player_detail"),
    path('player-create/', views.PlayerCreateView.as_view(), name="player_create"),
    path('batch-player-create/', views.BatchPlayerCreateView.as_view(), name="batch_player_create"),
    path('player-update/<int:pk>/', views.PlayerUpdateView.as_view(), name="player_update"),
    path('player-delete/<int:pk>/', views.PlayerDeleteView.as_view(), name="player_delete"),
    path('team-create/', views.TeamCreateView.as_view(), name="team_create"),
    path('team-detail/', views.TeamDetailView.as_view(), name="team_detail"),
    path('team-config/', views.TeamConfigView.as_view(), name="team_config"),
    path('team-delete/<int:pk>', views.TeamDeleteView.as_view(), name="team_delete"),
    path('team-choice/<int:pk>', views.TeamChoiceView.as_view(), name="team_choice"),
    path('notice-list/', views.NoticeListView.as_view(), name="notice_list"),
    path('notice/<int:pk>', views.NoticeDetailView.as_view(), name="notice"),
    path('recalc/<int:pk>', views.recalc, name="recalc"),
]

rankmaker/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include
from django.views.generic.base import TemplateView

from . import settings_common, settings_dev

urlpatterns = [
    path('kanri/', admin.site.urls),
    path('duel/', include('duel.urls')),
    path('multi/', include('multi.urls')),
    path('', include('entrance.urls')),
    path('accounts/', include('allauth.urls')),
    path("ads.txt", TemplateView.as_view(template_name='ads.txt', content_type='text/plain')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(
    settings_common.MEDIA_URL,
    document_root=settings_dev.MEDIA_ROOT,
)

multi/models.py
from django.utils import timezone
from datetime import datetime

from django.utils.timezone import make_aware

from accounts.models import CustomUser
from django.db import models
from model_utils import FieldTracker
from django.core.validators import MinLengthValidator, RegexValidator

# Create your models here.


class Team(models.Model):
    """チームモデル"""

    name = models.CharField(verbose_name='チーム名', max_length=50, default="<チーム名>")
    est_date = models.DateTimeField(verbose_name='登録日', auto_now_add=True)
    owner = models.ForeignKey(CustomUser, verbose_name='作成ユーザー', null=True, blank=True, on_delete=models.CASCADE)
    one_on_one = models.BooleanField(
        verbose_name='デフォルト入力方式',
        default=False,
        blank=True,
        help_text='対戦結果登録時に使用したい入力方式を選択できます'
    )
    description = models.TextField(
        verbose_name='説明',
        max_length=500,
        blank=True,
        null=True,
        help_text='チームの説明を入力します。ランキングをシェアした際に表示されます。'
    )
    page_id = models.CharField(
        verbose_name="キーフレーズ",
        max_length=20,
        blank=True,
        null=True,
        unique=True,
        validators=[
            MinLengthValidator(5, '5文字以上で設定してください'),
            RegexValidator(r'^[a-zA-Z0-9]*$', '使用可能な文字は半角英数字のみです')
        ]
    )
    offset_term = models.IntegerField(
        verbose_name="ボーナスタイム",
        blank=None,
        null=None,
        default=50,
        help_text='レーティングがぐんぐん上昇する「ボーナスタイム」の継続期間（試合数）を選択します。<br>この値を変更するとレーティングの再計算が必要になります。'
    )

    tracker = FieldTracker()

    class Meta:
        verbose_name_plural = 'Team'

    def __str__(self):
        return self.name


class Player(models.Model):
    """プレイヤーモデル"""

    team = models.ForeignKey(Team, verbose_name='所属', on_delete=models.CASCADE)
    name = models.CharField(verbose_name='プレイヤー', max_length=10000)
    inactive = models.BooleanField(verbose_name='引退', default=False, blank=True)
    ltst_rating = models.FloatField(verbose_name='最新の見かけレーティング', default=1000.0)

    class Meta:
        verbose_name_plural = 'Player'

    def match_exp(self):
        return Participant.objects.filter(player=self).count()

    def latest_rating(self, date):  # Participantを探って最新のレーティングを見つける
        record = Participant.objects.filter(player=self).filter(game__date__lt=date).order_by('-game__date').first()
        if record:
            return float(record.new_rating)
        else:
            return 1500.0

    def latest_appr(self, date):  # Participantを探って最新のレーティングを見つける
        record = Participant.objects.filter(player=self).filter(game__date__lt=date).order_by('-game__date__lt').first()

        if record:
            return float(record.new_appr)
        else:
            return 1000.0

    def now_rating(self):
        return self.latest_rating(make_aware(datetime.now()))

    def __str__(self):
        return format(self.name) + " (" + format(self.team.name) + ")"


class Affiliation(models.Model):
    """各ユーザーが選択中のチームを記録するテーブル"""
    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.CASCADE, related_name="br_affl_user")
    team = models.ForeignKey(
        Team,
        verbose_name='チーム',
        null=True,
        on_delete=models.SET_NULL,
        related_name="affl_team"
    )

    class Meta:
        verbose_name_plural = 'Affiliations'

    def __str__(self):
        return format(self.user) + " (" + format(self.team) + ")"


class Game(models.Model):
    """ゲームモデル"""
    name = models.CharField(verbose_name='試合名称', max_length=50, blank=True, null=True)
    team = models.ForeignKey(Team, verbose_name='チーム', on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name='試合日時', default=timezone.now)
    last_modify = models.DateTimeField(verbose_name="最終更新日", default=timezone.now)
    one_on_one = models.BooleanField(verbose_name="1対1対戦", default=False, blank=True)
    need_to_recalc = models.BooleanField(verbose_name="要再計算", default=False)
    memo = models.TextField(verbose_name="コメント", blank=True)
    tracker = FieldTracker()

    class Meta:
        verbose_name_plural = 'Game'

    def __str__(self):
        return format(self.id) +":"+ format(self.date, '%m%d') + "(" + format(self.team) + ")"


class Participant(models.Model):
    """Gameの参加者を追加するモデル"""
    game = models.ForeignKey(
        Game,
        verbose_name='ゲーム',
        on_delete=models.CASCADE,
        related_name='participant_game'
    )
    player = models.ForeignKey(
        Player,
        verbose_name='player',
        on_delete=models.CASCADE,
        related_name='participant_player'
    )
    rank = models.IntegerField(verbose_name='順位', default=0)
    new_rating = models.FloatField(verbose_name='対戦後のレーティング', default=1500.0)
    old_rating = models.FloatField(verbose_name='対戦前のレーティング', default=1500.0)
    rating_diff = models.FloatField(verbose_name='レーティング変化', default=0.0)
    new_appr = models.FloatField(verbose_name='対戦後のレーティング', default=1500.0)
    old_appr = models.FloatField(verbose_name='対戦前のレーティング', default=1500.0)
    appr_diff = models.FloatField(verbose_name='レーティング変化', default=0.0)

    class Meta:
        verbose_name_plural = 'Participants'

    def __str__(self):
        return format(self.game.id) + ":" + format(self.player) \
               + " pos: " + format(self.rank) + " R:" + format(self.new_rating)


class Duel(models.Model):
    """Gameを分解した一対一対戦"""
    game = models.ForeignKey(Game, verbose_name='対応するGame', on_delete=models.CASCADE, related_name='duel_game')
    winner = models.ForeignKey(Player, verbose_name='勝者', on_delete=models.CASCADE, related_name='duel_win')
    loser = models.ForeignKey(Player, verbose_name='敗者', on_delete=models.CASCADE, related_name='duel_los')
    even = models.BooleanField(verbose_name='引き分け')

    class Meta:
        verbose_name_plural = 'Duel'

    def __str__(self):

        return format(self.game.id) + ": " + format(self.winner.name) + "-" + format(self.loser) \
               + "(" + format(self.even) + ")"


class Rating(models.Model):
    """レーティングモデル"""

    player = models.ForeignKey(Player, verbose_name='プレイヤー', on_delete=models.CASCADE)
    duel = models.ForeignKey(Duel, verbose_name='マッチ', on_delete=models.CASCADE, related_name='rating_duel')
    rating_diff = models.FloatField(verbose_name='レーティング差分', default=0.0)

    class Meta:
        verbose_name_plural = 'Rating'

    def __str__(self):
        return format(self.player.name) + "(" + format(self.rating_diff) + ") @" + format(self.duel.game)


class Notice(models.Model):
    """お知らせ"""
    category_choices = (
        (1, 'お知らせ'),
        (2, '重要'),
    )

    title = models.CharField(verbose_name='タイトル', max_length=50)
    text = models.TextField(verbose_name='本文')
    release_date = models.DateTimeField(verbose_name='公開日', default=datetime.now)
    category = models.IntegerField(choices=category_choices, default=1)

    def __str__(self):
        return self.title

multi/templates/multi/base.html
{% load static %}

<html lang="ja">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content="ランクメーカーは、クイズサークルのレーティング計算作業から生まれた「チーム内ランキング算出システム」です。チーム内での対戦結果を登録することで、簡単にチーム内ランキングを作成できます。現在ベータテスト実施中です。"/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}"/>
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900"
          rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i"
          rel="stylesheet"/>

    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- My Style -->
    <link href="{% static 'css/mystyle.css' %}" rel="stylesheet"/>
    {% block head %}{% endblock %}
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-WCEV41YJYC"></script>
    <script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-WCEV41YJYC');


    </script>
    <!--Google AdSense-->
    <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4159868419764976"
     crossorigin="anonymous"></script>
</head>

<body>
{% load django_bootstrap5 %}
<div id="wrapper" class="bg-white">
    <!-- Navigation-->
    <nav class="navbar navbar-light bg-light sticky-top">
        <div class="container px-5">
            <a class="navbar-brand" href="{% block toplink %}{% endblock %}">ランクメーカー<sub>βテスト</sub></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav me-auto">
                    {% if user.is_authenticated %}
                    {% if user.have_multi_team %}
                    <li class="nav-item">
                        <a href="{% url 'multi:ranking' %}" class="nav-link {% block active_ranking %}{% endblock %}">ランキング</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'multi:game_list' %}"
                           class="nav-link {% block active_game_list %}{% endblock %}">対戦結果一覧</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'multi:player_list' %}"
                           class="nav-link {% block active_player_list %}{% endblock %}">メンバー一覧</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'multi:team_detail' %}"
                           class="nav-link {% block active_team_config %}{% endblock %}">チーム設定</a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'multi:notice_list' %}"
                           class="nav-link {% block active_notice_list %}{% endblock %}">お知らせ</a>
                    </li>
                    {% endif %}
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'account_logout' %}">ログアウト</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link {% block activate_signup %}{% endblock %}" href="{% url 'account_signup' %}">新規登録</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link {% block activate_login %}{% endblock %}" href="{% url 'account_login' %}">ログイン</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link {% block active_inquiry %}{% endblock %}"
                           href="https://docs.google.com/forms/d/e/1FAIpQLSed7pUc_baPBzLLRNsfcm95PLtAp_VSsevnOT3eQXS8yXPzyg/viewform?usp=sf_link">ご意見</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>


    <div class="container my-3">
        {% block header %}{% endblock %}
        {% if messages %}
        <ul class="clearfix mb-1" style="list-style: none;">
            {% for message in messages %}

            <li {% if message.tags %} class="float-md-end w-md-50 mb-0 {{ message.tags }}" {% endif %}>
                {{ message }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}


        {% block center %}{% endblock %}


    </div>

    <!-- Footer-->
    <footer class="py-4 bg-dark mt-auto mb-0">
        <div class="container px-5">
            <p class="mb-3 text-center text-white small">
                <a href="{% url 'entrance:rating_system' %}" class="link-light">
                    ランクメーカーの仕組み
                </a>
                　
                <a href="{% url 'entrance:privacy_policy' %}" class="link-light">
                    プライバシーポリシー
                </a>
            </p>
            <p class="m-0 text-center text-white small">Copyright &copy; ランクメーカー 2022</p>
        </div>
    </footer>

    <!-- Bootstrap core JS-->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"
            integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"
            integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
            crossorigin="anonymous"></script>
</body>
</html>

multi/templates/multi/game_list.html
{% extends 'multi/center.html' %}
{% load static %}

{% block title %}対戦結果一覧 | ランクメーカー{% endblock %}

{% block toplink %}{% url 'multi:home' %}{% endblock %}

{% block active_match_list %}active{% endblock %}

{% block head %}
{% endblock %}

{% block contents %}
<h4 class="bg-secondary text-white p-1">{{ team }}の対戦結果一覧</h4>
<div class="d-flex justify-content-end mb-4">
    <a class="btn btn-primary"
       href="{% if team.one_on_one %}{% url 'multi:game_create_1on1' %}{% else %}{% url 'multi:game_create' %}{% endif %}">対戦結果登録</a>
</div>
{% for game in game_list %}
<div class="row mx-0 mb-2 border">

    <a href="{% url 'multi:game_detail' game.pk %}" class="col-md-8 h2 mb-0 bg-light text-decoration-none">
        <!--pk=プライマリキー-->
        {{ game.name }}{% if game.name == '' %}タイトルなし{% endif %}
    </a>

    <div class="col-md-4 bg-light text-dark">
        <p class="text-start text-md-end mb-0">
            {{ game.date }}
        </p>
    </div>
    <a href="{% url 'multi:game_detail' game.pk %}" class="col-12 bg-light text-dark text-decoration-none">
        <!--pk=プライマリキー-->
        {% if game.need_to_recalc %}
        <form action="{% url 'multi:recalc' game.pk %}" method="post" class="m-0">
            {% csrf_token %}
            <button type="submit" class="badge bg-danger border-0" name="recalc_button_{{ game.pk }}">再計算</button>

        </form>
        {% endif %}
        {% for pl in game.participant_game.all|dictsort:"rank" %}
        {{ pl.rank }}位:{{pl.player.name}}({{pl.new_appr|floatformat:0}}){% if not forloop.last %}、{% endif %}
        {% endfor %}
    </a>
</div>

{% empty %}
<p>対戦結果がありません。</p>
{% endfor %}

<p class="small">
    ※古い対戦を編集した場合、より新しい試合の再計算が必要となる場合があります。<br>
    より古い対戦から順に<span class="badge bg-danger">再計算</span>をクリックして再計算してください。
</p>

<!--  ページネーション処理  -->
{% if is_paginated %}
<ul class="pagination">
    <!--前ページへのリンク-->
    {% if page_obj.has_previous %}
    <li class="page-item">
        <a href="?page={{ page_obj.previous_page_number }}" class="page-link">
            <span aria-hidden="true">&laquo;</span>
        </a>
    </li>
    {% endif %}

    <!--ページ数表示-->
    {% for page_num in page_obj.paginator.page_range %}
    {% if page_obj.number == page_num %}
    <li class="page-item active">
        <a href="#" class="page-link">{{page_num}}</a>
    </li>
    {% else %}
    <li class="page-item">
        <a href="?page={{ page_num }}" class="page-link">{{page_num}}</a>
    </li>
    {% endif %}
    {% endfor %}

    <!--次ページへのリンク-->
    {% if page_obj.has_next %}
    <li class="page-item">
        <a href="?page={{ page_obj.next_page_number }}" class="page-link">
            <span aria-hidden="true">&raquo;</span>
        </a>
    </li>
    {% endif %}
</ul>
{% endif %}
{% endblock %}

multi/templates/multi/home.html
{% extends 'multi/center.html' %}

{% load static %}

{% block title %}ランクメーカー{% endblock %}

{% block header %}{% endblock %}

{% block toplink %}{% url 'multi:home' %}{% endblock %}

{% block contents %}


<div>
    {% if user.have_multi_team %}
    <table class="table mb-0">
        <tr>
            <th colspan="3" class="bg-secondary text-white">{{team}} の最新ランキング</th>
        </tr>
        <tr>
            <th>順位</th>
            <th>名前</th>
            <th>レーティング</th>
        </tr>
        {% for player in ranking %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>{{ player.name }}</td>
            <td>{{ player.ltst_rating|floatformat:2 }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">メンバーが登録されていません。<a href="{% url 'multi:player_create' %}">メンバーの登録はこちらから。</a></td>
        </tr>
        {% endfor %}
    </table>

    {% if ranking.count != 0 %}
    <p class="text-end">
        <a href="{% url 'multi:ranking' %}">＞全てのランキングを表示</a>
    </p>
    {% endif %}
    {% else %}
    <p class="">チームが作成されていません。<br>
        <a href="{% url 'multi:team_create' %}">こちらからから作成してください。</a>
    </p>
    {% endif %}
</div>
<div class="mt-3">
    <table class="table mb-0">
        <tr>
            <th colspan="3" class="bg-secondary text-white">お知らせ</th>
        </tr>
        {% for article in notice %}
        <tr>
            <td>
                {% if article.category == 1 %}
                <span class="badge bg-info">{{ article.get_category_display }}</span>
                {% elif article.category == 2 %}
                <span class="badge bg-danger">{{ article.get_category_display }}</span>
                {% endif %}
            </td>
            <td><a href="{% url 'multi:notice' article.pk %}">{{ article.title }}</a></td>
            <td>{{ article.release_date }}</td>
        </tr>
        {% endfor %}
    </table>
    {% if article.count != 0 %}
    <p class="text-end">
        <a href="{% url 'multi:notice_list' %}">＞以前のお知らせを表示</a>
    </p>
    {% endif %}
</div>

{% endblock %}

multi/templates/multi/ranking.html
{% extends 'multi/center.html' %}

{% load static %}

{% block title %}ランキング表示｜ランクメーカー{% endblock %}

{% block active_ranking %}active{% endblock %}

{% block header %}

{% endblock %}

{% block toplink %}{% url 'multi:home' %}{% endblock %}

{% block contents %}

        <h4 class="bg-secondary text-white p-1">最新ランキング</h4>
        <div>
            <table class="table">
                <tr>
                    <th>順位</th>
                    <th>名前</th>
                    <th>レーティング</th>
                </tr>

                {% for player in ranking %}
                <tr>
                    <th>{{ forloop.counter }}</th>
                    <td>
                        <a href="{% url 'multi:player_detail' player.pk %}"  class="text-decoration-none">
                            {{ player.name }}
                        </a>
                    </td>
                    <td>{{ player.ltst_rating|floatformat:2 }}</td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="3">メンバーが登録されていません。<a href="{% url 'multi:player_create' %}">メンバーの登録はこちらから。</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>

{% endblock %}

multi/templates/multi/ranking_ext.html
{% extends 'multi/center.html' %}

{% load static %}

{% block title %}{{ team.name }} 最新ランキング｜ランクメーカー{% endblock %}

{% block active_ranking %}active{% endblock %}

{% block header %}

{% endblock %}

{% block toplink %}{% url 'multi:home' %}{% endblock %}

{% block contents %}

<h4 class="bg-secondary text-white p-1">{{ team.name }} 最新ランキング</h4>
<div>
    <p class="small border p-2">チーム説明：{{ team.description }}</p>
    <table class="table">
        <tr>
            <th>順位</th>
            <th>名前</th>
            <th>レーティング</th>
        </tr>

        {% for player in ranking %}
        <tr>
            <th>{{ forloop.counter }}</th>
            <td>
                <a href="{% url 'multi:player_detail' player.pk %}" class="text-decoration-none">
                    {{ player.name }}
                </a>
            </td>
            <td>{{ player.ltst_rating|floatformat:2 }}</td>
        </tr>
        {% empty %}
        <tr>
            <td colspan="3">メンバーが登録されていません。</td>
        </tr>
        {% endfor %}
    </table>
</div>
<p class="small text-end"><a href="{% url 'entrance:index' %}">＞トップページに戻る</a></p>


{% endblock %}

multi/templates/multi/team_config.html
{% extends 'multi/center.html' %}
{% load static %}

{% block title %}チーム設定 | ランクメーカー{% endblock %}

{% block active_team_config %}active{% endblock %}

{% block toplink %}{% url 'multi:home' %}{% endblock %}

{% block contents %}

<h4 class="bg-secondary text-white p-1">チーム情報</h4>
<div class="row">
    <p class="text-end">
        <a href="{% url 'multi:team_choice' affl.id %}" class="btn btn-primary">チーム変更</a>
    </p>
    <form class="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% include 'multi/form_fields_loop.html' %}
        <button class="btn btn-primary" type="submit" name="button_team_config">更新</button>
        <a href="{% url 'multi:team_detail'%}" class="btn btn-secondary ml-2">キャンセル</a>
    </form>
</div>
<div class="ml-auto">
    <p>
        <a href="{% url 'multi:team_create' %}" class="me-2">チームを追加する</a>
        <a href="{% url 'multi:team_delete' affl.team.id %}" class="ms-2">チームを削除する</a>
    </p>
</div>

{% endblock %}